theme: jekyll-theme-tactile
title: Drop7 Reinforcement Learning Challenge
description: The goal of this challenge is to create a Deep Learning algorithm capable of playing a game similar to Zynga’s Drop7.
